const { createApp } = Vue;
createApp({
    data() {
        return{
            firstName: "",
            lastName: "",
            street: "",
            state: "MN",
            availableStates: [
            { value: "AL", name: "ALABAMA"},
            { value: "AK", name: "ALASKA"},
            { value: "AZ", name: "ARIZONA"},
            { value: "AR", name: "ARKANSAS"},
            { value: "CA", name: "CALIFORNIA"},
            { value: "CO", name: "COLORADO"},
            { value: "CT", name: "CONNECTICUT"},
            { value: "DE", name: "DELAWARE"},
            { value: "DC", name: "DISTRICT OF COLUMBI"},
            { value: "FL", name: "FLORIDA"},
            { value: "GA", name: "GEORGIA"},
            { value: "GU", name: "GUAM"},
            { value: "HI", name: "HAWAII"},
            { value: "ID", name: "IDAHO"},
            { value: "IL", name: "ILLINOIS"},
            { value: "IN", name: "INDIANA"},
            { value: "IA", name: "IOWA"},
            { value: "KS", name: "KANSAS"},
            { value: "KY", name: "KENTUCKY"},
            { value: "LA", name: "LOUISIANA"},
            { value: "ME", name: "MAINE"},
            { value: "MD", name: "MARYLAND"},
            { value: "MA", name: "MASSACHUSETTS"},
            { value: "MI", name: "MICHIGAN"},
            { value: "MN", name: "MINNESOTA"},
            { value: "MS", name: "MISSISSIPPI"},
            { value: "MO", name: "MISSOURI"},
            { value: "MT", name: "MONTANA"},
            { value: "NE", name: "NEBRASKA"},
            { value: "NV", name: "NEVADA"},
            { value: "NH", name: "NEW HAMPSHIRE"},
            { value: "NJ", name: "NEW JERSEY"},
            { value: "NM", name: "NEW MEXICO"},
            { value: "NY", name: "NEW YORK"},
            { value: "NC", name: "NORTH CAROLINA"},
            { value: "ND", name: "NORTH DAKOTA"},
            { value: "OH", name: "OHIO"},
            { value: "OK", name: "OKLAHOMA"},
            { value: "OR", name: "OREGON"},
            { value: "PA", name: "PENNSYLVANIA"},
            { value: "RI", name: "RHODE ISLAND"},
            { value: "SC", name: "SOUTH CAROLINA"},
            { value: "SD", name: "SOUTH DAKOTA"},
            { value: "TN", name: "TENNESSEE"},
            { value: "TX", name: "TEXAS"},
            { value: "UT", name: "UTAH"},
            { value: "VT", name: "VERMONT"},
            { value: "VA", name: "VIRGINIA"},
            { value: "VI", name: "VIRGIN ISLANDS"},
            { value: "WA", name: "WASHINGTON"},
            { value: "WV", name: "WEST VIRGINIA"},
            { value: "WI", name: "WISCONSIN"},
            { value: "WY", name: "WYOMING"}],
            selectedColors: [],
            colors: [
                {name: "White", value: "white"},
                {name: "Beige", value: "beige"},
                {name: "Fawn (light, medium, dark)", value: "fawn"},
                {name: "Brown (light, medium, dark)", value: "brown"},
                {name: "Bay Black", value: "bay-black"},
                {name: "True Black", value: "true-black"},
                {name: "Rose Gray (light, medium, dark)", value: "rose-gray"},
                {name: "Silver Gray (light, medium, dark)", value: "silver-gray"},
            ],
            status: ""
        }
    }
}).mount("#alpacaForm");